language: python

jobs:
  include:
    # perform a linux build
    - services: docker
    # and a mac build for 3.6
    - os: osx
      language: shell
      python:
        - "3.6"
    # and a mac build for 3.7
    - os: osx
      language: shell
      python:
        - "3.7"
    # and a mac build for 3.8
    - os: osx
      language: shell
      python:
        - "3.8"
    # and a mac build for 3.9
    - os: osx
      language: shell
      python:
        - "3.9"
    # windows build 3.6
    - os: windows
      language: shell
      before_install:
        - choco install python --version 3.6
        - export PATH="/c/Python36:/c/Python36/Scripts:$PATH"
    # windows build 3.7
    - os: windows
      language: shell
      before_install:
        - choco install python --version 3.7
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
    # windows build 3.8
    - os: windows
      language: shell
      before_install:
        - choco install python --version 3.8
        - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"
    # windows build 3.9
    - os: windows
      language: shell
      before_install:
        - choco install python --version 3.8
        - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"

env:
  global:
    - CIBW_SKIP="cp27-* cp33-* cp34-* cp35-* *macosx_10_6*"
    - TWINE_USERNAME=__token__
    # Note: TWINE_PASSWORD is set to a PyPI API token in Travis settings

install:
  - python -m pip install twine cibuildwheel==1.1.0

script:
  # build the wheels, put them into './wheelhouse'
  - python -m cibuildwheel --output-dir wheelhouse

after_success:
  # if the release was tagged, upload them to PyPI
  - if [[ $TRAVIS_TAG ]]; then python -m twine upload wheelhouse/*.whl; fi